name: wielcy_polacy
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^5.0.3
  provider: ^5.0.0
  
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  fluttertoast: ^8.2.4
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  dots_indicator: ^2.0.0
  persistent_bottom_nav_bar: any

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

  


flutter:

  uses-material-design: true
  assets:
    - img/
    

  