// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR_DeX5T4qL3L5MOaE2hA3dEbKFOX5Mh0',
    appId: '1:694951995497:web:c88c71cdba19a5ade35af8',
    messagingSenderId: '694951995497',
    projectId: 'wielcy-polacy-5813b',
    authDomain: 'wielcy-polacy-5813b.firebaseapp.com',
    storageBucket: 'wielcy-polacy-5813b.appspot.com',
    measurementId: 'G-DZW20Q14DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdWuHTXyGquc0xHDon5Z82H1yBFOsfJnM',
    appId: '1:694951995497:android:1e111e89e1e0cf7be35af8',
    messagingSenderId: '694951995497',
    projectId: 'wielcy-polacy-5813b',
    storageBucket: 'wielcy-polacy-5813b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn1LuRN33XFiiH3ZsOtW4S0lQhK5FX8PY',
    appId: '1:694951995497:ios:bb0df4ae5e11dad9e35af8',
    messagingSenderId: '694951995497',
    projectId: 'wielcy-polacy-5813b',
    storageBucket: 'wielcy-polacy-5813b.appspot.com',
    iosBundleId: 'com.example.wielcyPolacy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn1LuRN33XFiiH3ZsOtW4S0lQhK5FX8PY',
    appId: '1:694951995497:ios:59e25e1efe3ee846e35af8',
    messagingSenderId: '694951995497',
    projectId: 'wielcy-polacy-5813b',
    storageBucket: 'wielcy-polacy-5813b.appspot.com',
    iosBundleId: 'com.example.wielcyPolacy.RunnerTests',
  );
}
